project:
  type: website
  output-dir: _site

website:
  title: "100DaysOfData"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/VineetLoyer/100DaysOfData
        aria-label: Github
      - icon: linkedin
        href: https://www.linkedin.com/in/vineet-loyer/
        aria-label: LinkedIn
  

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toggle-theme: true
    toc: true



